//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneGuitarTab.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoneGuitarTab.UI.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is an open source project and is licensed under Microsoft Public License (Ms-PL)..
        /// </summary>
        public static string About_AppDescription {
            get {
                return ResourceManager.GetString("About_AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team invites developers &amp;amp; designers to join us to improve the best tablature app on the Store..
        /// </summary>
        public static string About_AppInvitation {
            get {
                return ResourceManager.GetString("About_AppInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneGuitarTab.
        /// </summary>
        public static string About_AppTitle {
            get {
                return ResourceManager.GetString("About_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://phoneguitartab.codeplex.com.
        /// </summary>
        public static string About_CompanyUrl {
            get {
                return ResourceManager.GetString("About_CompanyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2011-2014 Phone guitar tab.
        /// </summary>
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://facebook.com/PhoneGuitarTab.
        /// </summary>
        public static string About_FacebookUrl {
            get {
                return ResourceManager.GetString("About_FacebookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support.
        /// </summary>
        public static string About_Support {
            get {
                return ResourceManager.GetString("About_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phoneguitartab@gmail.com.
        /// </summary>
        public static string About_SupportEmail {
            get {
                return ResourceManager.GetString("About_SupportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Guitar Tab.
        /// </summary>
        public static string AppTitle_Lower {
            get {
                return ResourceManager.GetString("AppTitle_Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE GUITAR TAB.
        /// </summary>
        public static string AppTitle_Upper {
            get {
                return ResourceManager.GetString("AppTitle_Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, we cannot handle this error. If it repeats every time, please reinstall application. Then, you can download previous synchronized tabs using synchronization feature. Error details:.
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more online.
        /// </summary>
        public static string Group_More {
            get {
                return ResourceManager.GetString("Group_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bands.
        /// </summary>
        public static string Panarama_Bands {
            get {
                return ResourceManager.GetString("Panarama_Bands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recent.
        /// </summary>
        public static string Panarama_History {
            get {
                return ResourceManager.GetString("Panarama_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        public static string Panarama_Other {
            get {
                return ResourceManager.GetString("Panarama_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabs.
        /// </summary>
        public static string Panarama_Tabs {
            get {
                return ResourceManager.GetString("Panarama_Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have nothing downloaded yet..
        /// </summary>
        public static string PanaramaTabs_NoTabs {
            get {
                return ResourceManager.GetString("PanaramaTabs_NoTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string RelativeDate_Day {
            get {
                return ResourceManager.GetString("RelativeDate_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string RelativeDate_Days {
            get {
                return ResourceManager.GetString("RelativeDate_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  an hour ago.
        /// </summary>
        public static string RelativeDate_Hour {
            get {
                return ResourceManager.GetString("RelativeDate_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string RelativeDate_Hours {
            get {
                return ResourceManager.GetString("RelativeDate_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  a minute ago.
        /// </summary>
        public static string RelativeDate_Minute {
            get {
                return ResourceManager.GetString("RelativeDate_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} minutes ago.
        /// </summary>
        public static string RelativeDate_Minutes {
            get {
                return ResourceManager.GetString("RelativeDate_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last month.
        /// </summary>
        public static string RelativeDate_Month {
            get {
                return ResourceManager.GetString("RelativeDate_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        public static string RelativeDate_Months {
            get {
                return ResourceManager.GetString("RelativeDate_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a second ago.
        /// </summary>
        public static string RelativeDate_Second {
            get {
                return ResourceManager.GetString("RelativeDate_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        public static string RelativeDate_Seconds {
            get {
                return ResourceManager.GetString("RelativeDate_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last year.
        /// </summary>
        public static string RelativeDate_Year {
            get {
                return ResourceManager.GetString("RelativeDate_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        public static string RelativeDate_Years {
            get {
                return ResourceManager.GetString("RelativeDate_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot download the tab right now..
        /// </summary>
        public static string Search_DownloadFailed {
            get {
                return ResourceManager.GetString("Search_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}...
        /// </summary>
        public static string Search_Downloading {
            get {
                return ResourceManager.GetString("Search_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string Search_Error {
            get {
                return ResourceManager.GetString("Search_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection available..
        /// </summary>
        public static string Search_NoInternetConnection {
            get {
                return ResourceManager.GetString("Search_NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, nothing found. 
        ///Try Searching with a comma: 
        ///band name, song name.
        /// </summary>
        public static string Search_NothingFound {
            get {
                return ResourceManager.GetString("Search_NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not perform operation.
        /// </summary>
        public static string Search_OperationFailed {
            get {
                return ResourceManager.GetString("Search_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} for {1}...
        /// </summary>
        public static string Search_PageFor {
            get {
                return ResourceManager.GetString("Search_PageFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string Search_SearchButton {
            get {
                return ResourceManager.GetString("Search_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search by.
        /// </summary>
        public static string Search_SearchBy {
            get {
                return ResourceManager.GetString("Search_SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for {0}...
        /// </summary>
        public static string Search_SearchFor {
            get {
                return ResourceManager.GetString("Search_SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected type.
        /// </summary>
        public static string Search_SelectedType {
            get {
                return ResourceManager.GetString("Search_SelectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t reach the server right now..
        /// </summary>
        public static string Search_ServerUnavailable {
            get {
                return ResourceManager.GetString("Search_ServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry,.
        /// </summary>
        public static string Search_Sorry {
            get {
                return ResourceManager.GetString("Search_Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  was downloaded.
        /// </summary>
        public static string Search_TabDownloadedText {
            get {
                return ResourceManager.GetString("Search_TabDownloadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; by {1}.
        /// </summary>
        public static string Search_TabDownloadedTitle {
            get {
                return ResourceManager.GetString("Search_TabDownloadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAB SEARCH.
        /// </summary>
        public static string Search_TabSearchTitle {
            get {
                return ResourceManager.GetString("Search_TabSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type here...
        /// </summary>
        public static string Search_TypePrompt {
            get {
                return ResourceManager.GetString("Search_TypePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online.
        /// </summary>
        public static string SearchForBand_Online {
            get {
                return ResourceManager.GetString("SearchForBand_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all tabs.
        /// </summary>
        public static string SearchTabType_All {
            get {
                return ResourceManager.GetString("SearchTabType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bass tabs.
        /// </summary>
        public static string SearchTabType_Bass {
            get {
                return ResourceManager.GetString("SearchTabType_Bass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chords.
        /// </summary>
        public static string SearchTabType_Chords {
            get {
                return ResourceManager.GetString("SearchTabType_Chords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drum tabs.
        /// </summary>
        public static string SearchTabType_Drum {
            get {
                return ResourceManager.GetString("SearchTabType_Drum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guitar tabs.
        /// </summary>
        public static string SearchTabType_Guitar {
            get {
                return ResourceManager.GetString("SearchTabType_Guitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guitar pro.
        /// </summary>
        public static string SearchTabType_GuitarPro {
            get {
                return ResourceManager.GetString("SearchTabType_GuitarPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to band name.
        /// </summary>
        public static string SearchType_Band {
            get {
                return ResourceManager.GetString("SearchType_Band", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to band, song.
        /// </summary>
        public static string SearchType_BandSong {
            get {
                return ResourceManager.GetString("SearchType_BandSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to song name.
        /// </summary>
        public static string SearchType_Song {
            get {
                return ResourceManager.GetString("SearchType_Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string Startup_About {
            get {
                return ResourceManager.GetString("Startup_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Startup_Delete {
            get {
                return ResourceManager.GetString("Startup_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate the app.
        /// </summary>
        public static string Startup_RateApp {
            get {
                return ResourceManager.GetString("Startup_RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string Startup_Select {
            get {
                return ResourceManager.GetString("Startup_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync with OneDrive.
        /// </summary>
        public static string Startup_Syncronize {
            get {
                return ResourceManager.GetString("Startup_Syncronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab search.
        /// </summary>
        public static string Startup_TabSearch {
            get {
                return ResourceManager.GetString("Startup_TabSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoscroll.
        /// </summary>
        public static string Stave_Autoscroll {
            get {
                return ResourceManager.GetString("Stave_Autoscroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instruments.
        /// </summary>
        public static string Stave_Instruments {
            get {
                return ResourceManager.GetString("Stave_Instruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading guitar pro content...
        /// </summary>
        public static string Stave_Loading {
            get {
                return ResourceManager.GetString("Stave_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation to this page failed, check your internet connection.
        /// </summary>
        public static string Stave_NavigationFailed {
            get {
                return ResourceManager.GetString("Stave_NavigationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin this tab.
        /// </summary>
        public static string Stave_Pin {
            get {
                return ResourceManager.GetString("Stave_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scale.
        /// </summary>
        public static string Stave_Scale {
            get {
                return ResourceManager.GetString("Stave_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option is useful if you removed all tabs from your phone and want to get them back from OneDrive.
        /// </summary>
        public static string Synchronize_Message {
            get {
                return ResourceManager.GetString("Synchronize_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive.
        /// </summary>
        public static string Synchronize_OneDrive {
            get {
                return ResourceManager.GetString("Synchronize_OneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restore all tabs.
        /// </summary>
        public static string Synchronize_RestoreAll {
            get {
                return ResourceManager.GetString("Synchronize_RestoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start!.
        /// </summary>
        public static string Synchronize_Start {
            get {
                return ResourceManager.GetString("Synchronize_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tabs downloaded - {1} tabs uploaded..
        /// </summary>
        public static string Synchronize_TabProcessed {
            get {
                return ResourceManager.GetString("Synchronize_TabProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYNCHRONIZE.
        /// </summary>
        public static string Synchronize_Title {
            get {
                return ResourceManager.GetString("Synchronize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to OneDrive....
        /// </summary>
        public static string Syncronize_Connecting {
            get {
                return ResourceManager.GetString("Syncronize_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  this song.
        /// </summary>
        public static string Tab_ConnectDevicePhraseEnd {
            get {
                return ResourceManager.GetString("Tab_ConnectDevicePhraseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect your device to internet to play.
        /// </summary>
        public static string Tab_ConnectDevicePhraseStart {
            get {
                return ResourceManager.GetString("Tab_ConnectDevicePhraseStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the app?.
        /// </summary>
        public static string Tab_RateTheApp {
            get {
                return ResourceManager.GetString("Tab_RateTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying the app? Motivate us by rating and reviewing it..
        /// </summary>
        public static string Tab_ReviewTheApp {
            get {
                return ResourceManager.GetString("Tab_ReviewTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string TemplateSearch_Download {
            get {
                return ResourceManager.GetString("TemplateSearch_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string TemplateSearch_Downloaded {
            get {
                return ResourceManager.GetString("TemplateSearch_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version:.
        /// </summary>
        public static string TemplateSearch_Version {
            get {
                return ResourceManager.GetString("TemplateSearch_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to votes:.
        /// </summary>
        public static string TemplateSearch_Votes {
            get {
                return ResourceManager.GetString("TemplateSearch_Votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoscroll.
        /// </summary>
        public static string TextTab_Autoscroll {
            get {
                return ResourceManager.GetString("TextTab_Autoscroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin this tab.
        /// </summary>
        public static string TextTab_Pin {
            get {
                return ResourceManager.GetString("TextTab_Pin", resourceCulture);
            }
        }
    }
}
