//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneGuitarTab.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoneGuitarTab.UI.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneGuitarTab.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://phoneguitartab.codeplex.com.
        /// </summary>
        internal static string CompanyUrl {
            get {
                return ResourceManager.GetString("CompanyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2011-2014 Phone guitar tab.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://facebook.com/PhoneGuitarTab.
        /// </summary>
        internal static string FacebookUrl {
            get {
                return ResourceManager.GetString("FacebookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like this app and think others might find this application useful, sharing your experience in a short review would be highly appreciated:.
        /// </summary>
        internal static string ReviewTheApp {
            get {
                return ResourceManager.GetString("ReviewTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phoneguitartab@gmail.com.
        /// </summary>
        internal static string SupportEmail {
            get {
                return ResourceManager.GetString("SupportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple application for searching, storing and viewing text guitar tablatures. For technical support or when you have suggestions or comments, don&apos;t hesitate to contact us at phoneguitartab@gmail.com.
        /// </summary>
        internal static string SupportMessage {
            get {
                return ResourceManager.GetString("SupportMessage", resourceCulture);
            }
        }
    }
}
